#!/usr/bin/env bash
# bootstrap.sh git setup: the repo ships no identity, delta config lives in its
# own generated file, and a user's ~/.gitconfig.local is never overwritten.
set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
failures=0

pass() { printf '   ok   %s\n' "$1"; }
fail() { printf '   FAIL %s\n' "$1"; failures=$((failures + 1)); }
check() { if eval "$2"; then pass "$1"; else fail "$1"; fi; }

# A PATH with only what the functions under test need, so `delta` is present
# exactly when a test puts a fake one in $WORK/bin.
mkdir -p "$WORK/bin"
for tool in git head rm cat mkdir basename dirname uname id; do
  ln -s "$(command -v "$tool")" "$WORK/bin/$tool"
done
with_delta()    { printf '#!/bin/sh\n' > "$WORK/bin/delta"; chmod +x "$WORK/bin/delta"; }
without_delta() { rm -f "$WORK/bin/delta"; }

# fresh $HOME with the stowed git config in place
new_home() {
  HOME_DIR="$WORK/home-$1"
  mkdir -p "$HOME_DIR/.config/git"
  cp "$DOTFILES/git/.config/git/config" "$HOME_DIR/.config/git/config"
}

# run bootstrap helpers non-interactively against $HOME_DIR
run() {
  HOME="$HOME_DIR" PATH="$WORK/bin" GIT_CONFIG_NOSYSTEM=1 ASSUME_YES=1 \
    BOOTSTRAP_SOURCE_ONLY=1 "$BASH" -c ". '$DOTFILES/bootstrap.sh'; $1" >/dev/null 2>&1
}
git_in_home() { HOME="$HOME_DIR" GIT_CONFIG_NOSYSTEM=1 git "$@"; }

echo ">> repo git config"
check "ships no user.name / user.email" \
  "! grep -qE '^[[:space:]]*(name|email)[[:space:]]*=' '$DOTFILES/git/.config/git/config'"
check "sets user.useConfigOnly" \
  "[ \"\$(git config --file '$DOTFILES/git/.config/git/config' user.useConfigOnly)\" = true ]"

echo ">> fresh machine, delta installed"
new_home fresh; with_delta; run 'setup_git_delta; setup_git_identity'
check "writes ~/.gitconfig.delta" "[ -f '$HOME_DIR/.gitconfig.delta' ]"
check "delta is the pager" "[ \"\$(git_in_home config core.pager)\" = delta ]"
check "creates no ~/.gitconfig.local without a tty" "[ ! -e '$HOME_DIR/.gitconfig.local' ]"
check "no identity is configured" "! git_in_home config user.email >/dev/null"
git_in_home init -q "$WORK/repo"
check "git refuses to commit without an identity" \
  "! git_in_home -C '$WORK/repo' commit -q --allow-empty -m test >/dev/null 2>&1"
check "creates an empty ~/.gitconfig" "[ -f '$HOME_DIR/.gitconfig' ] && [ ! -s '$HOME_DIR/.gitconfig' ]"
git_in_home config --global user.email probe@example.com
check "git config --global writes to ~/.gitconfig, not the stowed file" \
  "grep -q probe '$HOME_DIR/.gitconfig' && ! grep -q probe '$HOME_DIR/.config/git/config'"

echo ">> migration from the old layout"
new_home migrate; with_delta
printf '# GENERATED by bootstrap.sh - included from ~/.config/git/config\n[core]\n\tpager = delta\n' \
  > "$HOME_DIR/.gitconfig.local"
run setup_git_delta
check "removes the old generated ~/.gitconfig.local" "[ ! -e '$HOME_DIR/.gitconfig.local' ]"
check "writes ~/.gitconfig.delta instead" "[ -f '$HOME_DIR/.gitconfig.delta' ]"

echo ">> user-owned ~/.gitconfig.local"
new_home user; with_delta
printf '[user]\n\tname = Someone\n\temail = someone@example.com\n' > "$HOME_DIR/.gitconfig.local"
cp "$HOME_DIR/.gitconfig.local" "$WORK/expected"
run 'setup_git_delta; setup_git_identity'
check "is left untouched" "cmp -s '$HOME_DIR/.gitconfig.local' '$WORK/expected'"
check "provides the identity" "[ \"\$(git_in_home config user.email)\" = someone@example.com ]"

echo ">> delta not installed"
new_home nodelta; with_delta; run setup_git_delta; without_delta; run setup_git_delta
check "removes a stale ~/.gitconfig.delta" "[ ! -e '$HOME_DIR/.gitconfig.delta' ]"
check "falls back to the default pager" "! git_in_home config core.pager >/dev/null"

[ "$failures" -eq 0 ] || { echo "$failures failure(s)"; exit 1; }
