# GENERATED by rootloops/apply.sh from palette.env - do not edit by hand.
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} \
  --color=fg:#cdd5eb,fg+:#c0cae5,bg:#192036,bg+:#2b3554 \
  --color=hl:#28c8b1,hl+:#30e1c7,info:#f49437,marker:#a1bd22 \
  --color=prompt:#fb80aa,spinner:#bd97fc,pointer:#bd97fc,header:#56b8f7 \
  --color=border:#4b5987,label:#909fcc,query:#cdd5eb"
