# GENERATED by rootloops/apply.sh from palette.env - do not edit by hand.
# Re-colors the current terminal session to the Root Loops palette.
if [ -t 1 ] && [ -z "${ROOTLOOPS_TERM_APPLIED:-}" ]; then
  _rl() {
    if [ -n "${TMUX:-}" ]; then printf "\033Ptmux;\033\033]%s\007\033\\" "$1"
    else printf "\033]%s\007" "$1"; fi
  }
  _rl '10;#cdd5eb'
  _rl '11;#192036'
  _rl '4;0;#2b3554;1;#fb80aa;2;#a1bd22;3;#f49437;4;#56b8f7;5;#bd97fc;6;#28c8b1;7;#909fcc;8;#4b5987;9;#fda7c1;10;#b5d427;11;#fcb173;12;#89cdfc;13;#ceb5fd;14;#30e1c7;15;#c0cae5'
  unset -f _rl
  export ROOTLOOPS_TERM_APPLIED=1
fi
