#!/usr/bin/env bash
# Render every generated Root Loops color file from ./palette.env.
# Idempotent: safe to run any time, re-run after editing palette.env.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(dirname "$here")"

# shellcheck source=/dev/null
. "$here/palette.env"

recipe="$(head -n1 "$here/RECIPE")"
stamp="GENERATED by rootloops/apply.sh from palette.env - do not edit by hand."

c() { eval "printf '%s' \"\$RL_COLOR$1\""; }   # c 5 -> hex of RL_COLOR5

gen_ghostty_theme() {   # <palette-file> <out-file>
  ( # shellcheck source=/dev/null
    . "$1"
    echo "# $stamp"
    echo "background = $RL_BG"
    echo "foreground = $RL_FG"
    for i in $(seq 0 15); do echo "palette = $i=#$(c "$i")"; done
  ) > "$2"
}

# ---------------------------------------------------------------------------
# 1. Ghostty themes. The config uses
#    `theme = light:rootloops-light,dark:rootloops-dark` for auto light/dark.
#    rootloops.sh only makes dark schemes, so the light one is derived.
# ---------------------------------------------------------------------------
command -v python3 >/dev/null 2>&1 && python3 "$here/derive-light.py" || true
mkdir -p "$repo/ghostty/.config/ghostty/themes"
gen_ghostty_theme "$here/palette.env" "$repo/ghostty/.config/ghostty/themes/rootloops-dark"
if [ -f "$here/palette-light.env" ]; then
  gen_ghostty_theme "$here/palette-light.env" "$repo/ghostty/.config/ghostty/themes/rootloops-light"
fi
rm -f "$repo/ghostty/.config/ghostty/rootloops"   # old single-palette file

# ---------------------------------------------------------------------------
# 2. fzf - its UI chrome does not inherit 16-ANSI cleanly, so give it hex.
#    Sourced by the shell; appends to whatever FZF_DEFAULT_OPTS omnishell set.
# ---------------------------------------------------------------------------
{
  echo "# $stamp"
  echo "export FZF_DEFAULT_OPTS=\"\${FZF_DEFAULT_OPTS:-} \\"
  echo "  --color=fg:#$RL_FG,fg+:#$(c 15),bg:#$RL_BG,bg+:#$(c 0) \\"
  echo "  --color=hl:#$(c 6),hl+:#$(c 14),info:#$(c 3),marker:#$(c 2) \\"
  echo "  --color=prompt:#$(c 1),spinner:#$(c 5),pointer:#$(c 5),header:#$(c 4) \\"
  echo "  --color=border:#$(c 8),label:#$(c 7),query:#$RL_FG\""
} > "$repo/shell.d/70-fzf-colors.sh"

# ---------------------------------------------------------------------------
# 3. The OSC 4/10/11 palette push to the running terminal is handled by
#    omnishell's `root-loops` module now (see ../omnishell/config.toml), so it
#    is no longer generated here. This script only renders the emulator config
#    files that omnishell's module does not cover.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# 4. Neovim base16 palette (only if the nvim package exists yet - Phase 3)
# ---------------------------------------------------------------------------
if [ -d "$repo/nvim/.config/nvim" ]; then
  mkdir -p "$repo/nvim/.config/nvim/lua"
  {
    echo "-- $stamp"
    echo "-- recipe: $recipe"
    echo "return {"
    echo "  bg = \"#$RL_BG\", fg = \"#$RL_FG\","
    for i in $(seq 0 15); do
      echo "  color$i = \"#$(c "$i")\","
    done
    echo "}"
  } > "$repo/nvim/.config/nvim/lua/rootloops_palette.lua"
  echo "wrote nvim/.config/nvim/lua/rootloops_palette.lua"
fi

# ---------------------------------------------------------------------------
# 5. macOS Terminal.app profile (it ignores OSC escapes; needs an import)
# ---------------------------------------------------------------------------
if command -v python3 >/dev/null 2>&1; then
  python3 "$here/gen-terminal-app.py"
else
  echo "skipped RootLoops.terminal (no python3); committed copy is used as-is"
fi

# ---------------------------------------------------------------------------
# 6. GNOME Terminal / VTE default profile (Linux, persistent; best-effort)
# ---------------------------------------------------------------------------
if [ "$(uname -s)" = "Linux" ]; then
  bash "$here/gen-vte-terminal.sh" || true
fi

echo "wrote ghostty/.config/ghostty/themes/rootloops-{dark,light}"
echo "wrote shell.d/70-fzf-colors.sh"
echo "Root Loops applied. Reload your shell / terminal to see the changes."
