#!/usr/bin/env bash
# Render every generated Root Loops color file from ./palette.env.
# Idempotent: safe to run any time, re-run after editing palette.env.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(dirname "$here")"

# shellcheck source=/dev/null
. "$here/palette.env"

recipe="$(head -n1 "$here/RECIPE")"
stamp="GENERATED by rootloops/apply.sh from palette.env - do not edit by hand."

c() { eval "printf '%s' \"\$RL_COLOR$1\""; }   # c 5 -> hex of RL_COLOR5

gen_ghostty_theme() {   # <palette-file> <out-file>
  ( . "$1"
    echo "# $stamp"
    echo "background = $RL_BG"
    echo "foreground = $RL_FG"
    for i in $(seq 0 15); do eval "h=\$RL_COLOR$i"; echo "palette = $i=#$h"; done
  ) > "$2"
}

# ---------------------------------------------------------------------------
# 1. Ghostty themes. The config uses
#    `theme = light:rootloops-light,dark:rootloops-dark` for auto light/dark.
#    rootloops.sh only makes dark schemes, so the light one is derived.
# ---------------------------------------------------------------------------
command -v python3 >/dev/null 2>&1 && python3 "$here/derive-light.py" || true
mkdir -p "$repo/ghostty/.config/ghostty/themes"
gen_ghostty_theme "$here/palette.env" "$repo/ghostty/.config/ghostty/themes/rootloops-dark"
if [ -f "$here/palette-light.env" ]; then
  gen_ghostty_theme "$here/palette-light.env" "$repo/ghostty/.config/ghostty/themes/rootloops-light"
fi
rm -f "$repo/ghostty/.config/ghostty/rootloops"   # old single-palette file

# ---------------------------------------------------------------------------
# 2. fzf - its UI chrome does not inherit 16-ANSI cleanly, so give it hex.
#    Sourced by the shell; appends to whatever FZF_DEFAULT_OPTS omnishell set.
# ---------------------------------------------------------------------------
{
  echo "# $stamp"
  echo "export FZF_DEFAULT_OPTS=\"\${FZF_DEFAULT_OPTS:-} \\"
  echo "  --color=fg:#$RL_FG,fg+:#$(c 15),bg:#$RL_BG,bg+:#$(c 0) \\"
  echo "  --color=hl:#$(c 6),hl+:#$(c 14),info:#$(c 3),marker:#$(c 2) \\"
  echo "  --color=prompt:#$(c 1),spinner:#$(c 5),pointer:#$(c 5),header:#$(c 4) \\"
  echo "  --color=border:#$(c 8),label:#$(c 7),query:#$RL_FG\""
} > "$repo/shell.d/70-fzf-colors.sh"

# ---------------------------------------------------------------------------
# 3. Push the palette to whatever terminal is running, via OSC 4/10/11.
#    This is the terminal-agnostic path: no emulator config needed. Works in
#    any terminal that honors OSC (kitty, alacritty, wezterm, foot, konsole,
#    gnome-terminal, xterm, VTE apps, iTerm2, Linux console). macOS Terminal.app
#    is the notable holdout - it just ignores it. Harmless everywhere.
# ---------------------------------------------------------------------------
osc4=""
for i in $(seq 0 15); do
  osc4="$osc4$i;#$(c "$i");"
done
osc4="${osc4%;}"
{
  echo "# $stamp"
  echo '# Re-colors the current terminal session to the Root Loops palette.'
  echo 'if [ -t 1 ] && [ -z "${ROOTLOOPS_TERM_APPLIED:-}" ]; then'
  echo '  _rl() {'
  echo '    if [ -n "${TMUX:-}" ]; then printf "\033Ptmux;\033\033]%s\007\033\\" "$1"'
  echo '    else printf "\033]%s\007" "$1"; fi'
  echo '  }'
  echo "  _rl '10;#$RL_FG'"
  echo "  _rl '11;#$RL_BG'"
  echo "  _rl '4;$osc4'"
  echo '  unset -f _rl'
  echo '  export ROOTLOOPS_TERM_APPLIED=1'
  echo 'fi'
} > "$repo/shell.d/95-rootloops-term.sh"

# ---------------------------------------------------------------------------
# 4. Neovim base16 palette (only if the nvim package exists yet - Phase 3)
# ---------------------------------------------------------------------------
if [ -d "$repo/nvim/.config/nvim" ]; then
  mkdir -p "$repo/nvim/.config/nvim/lua"
  {
    echo "-- $stamp"
    echo "-- recipe: $recipe"
    echo "return {"
    echo "  bg = \"#$RL_BG\", fg = \"#$RL_FG\","
    for i in $(seq 0 15); do
      echo "  color$i = \"#$(c "$i")\","
    done
    echo "}"
  } > "$repo/nvim/.config/nvim/lua/rootloops_palette.lua"
  echo "wrote nvim/.config/nvim/lua/rootloops_palette.lua"
fi

# ---------------------------------------------------------------------------
# 5. macOS Terminal.app profile (it ignores OSC escapes; needs an import)
# ---------------------------------------------------------------------------
if command -v python3 >/dev/null 2>&1; then
  python3 "$here/gen-terminal-app.py"
else
  echo "skipped RootLoops.terminal (no python3); committed copy is used as-is"
fi

# ---------------------------------------------------------------------------
# 6. GNOME Terminal / VTE default profile (Linux, persistent; best-effort)
# ---------------------------------------------------------------------------
if [ "$(uname -s)" = "Linux" ]; then
  bash "$here/gen-vte-terminal.sh" || true
fi

echo "wrote ghostty/.config/ghostty/themes/rootloops-{dark,light}"
echo "wrote shell.d/70-fzf-colors.sh"
echo "wrote shell.d/95-rootloops-term.sh"
echo "Root Loops applied. Reload your shell / terminal to see the changes."
