#!/usr/bin/env python3
"""Generate a macOS Terminal.app profile (`RootLoops.terminal`) from palette.env.

Terminal.app cannot change its palette at runtime via OSC escapes (unlike every
other terminal we target), and it stores colors as archived NSColor blobs. So we
emit an importable `.terminal` profile instead. bootstrap.sh imports it on macOS.

Run by rootloops/apply.sh when python3 is available; the result is committed too.
"""
import plistlib
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent


def load_palette(path: pathlib.Path) -> dict:
    out = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def nscolor(hexstr: str) -> bytes:
    """Archived NSColor (calibrated RGB), as a binary-plist NSKeyedArchiver blob.

    This is the same shape Terminal.app writes itself and that the widely used
    iTerm2-Color-Schemes `.terminal` generator produces.
    """
    h = hexstr.lstrip("#")
    r, g, b = (int(h[i : i + 2], 16) / 255.0 for i in (0, 2, 4))
    rgb = f"{r:.17g} {g:.17g} {b:.17g}\x00".encode("ascii")
    archive = {
        "$version": 100000,
        "$archiver": "NSKeyedArchiver",
        "$top": {"root": plistlib.UID(1)},
        "$objects": [
            "$null",
            {
                "$class": plistlib.UID(2),
                "NSColorSpace": 1,  # NSCalibratedRGBColorSpace
                "NSRGB": rgb,
            },
            {
                "$classname": "NSColor",
                "$classes": ["NSColor", "NSObject"],
            },
        ],
    }
    return plistlib.dumps(archive, fmt=plistlib.FMT_BINARY)


def main() -> int:
    pal = load_palette(HERE / "palette.env")
    recipe = (HERE / "RECIPE").read_text().splitlines()[0]

    def col(key):
        return nscolor(pal[key])

    ansi = [f"RL_COLOR{i}" for i in range(16)]
    profile = {
        "name": "Root Loops",
        "type": "Window Settings",
        "ProfileCurrentVersion": 2.06,
        "BackgroundColor": nscolor(pal["RL_BG"]),
        "TextColor": nscolor(pal["RL_FG"]),
        "TextBoldColor": nscolor(pal["RL_COLOR15"]),
        "CursorColor": nscolor(pal["RL_COLOR7"]),
        "SelectionColor": nscolor(pal["RL_COLOR0"]),
        "ANSIBlackColor": col(ansi[0]),
        "ANSIRedColor": col(ansi[1]),
        "ANSIGreenColor": col(ansi[2]),
        "ANSIYellowColor": col(ansi[3]),
        "ANSIBlueColor": col(ansi[4]),
        "ANSIMagentaColor": col(ansi[5]),
        "ANSICyanColor": col(ansi[6]),
        "ANSIWhiteColor": col(ansi[7]),
        "ANSIBrightBlackColor": col(ansi[8]),
        "ANSIBrightRedColor": col(ansi[9]),
        "ANSIBrightGreenColor": col(ansi[10]),
        "ANSIBrightYellowColor": col(ansi[11]),
        "ANSIBrightBlueColor": col(ansi[12]),
        "ANSIBrightMagentaColor": col(ansi[13]),
        "ANSIBrightCyanColor": col(ansi[14]),
        "ANSIBrightWhiteColor": col(ansi[15]),
    }

    dst = HERE / "RootLoops.terminal"
    header = f"<!-- GENERATED by rootloops/gen-terminal-app.py - recipe: {recipe} -->\n"
    data = plistlib.dumps(profile, fmt=plistlib.FMT_XML)
    # slip a comment in after the doctype line
    lines = data.decode().splitlines(keepends=True)
    lines.insert(2, header)
    dst.write_text("".join(lines))
    print(f"wrote {dst.relative_to(HERE.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
